### ISSUE TITLE
Conditional jobs and steps

### ISSUE THREAD

**Issue by SethMichaelLarson** [SethMichaelLarson/Armonaut#38]
```yaml

jobs:
  - env: ENV=1
    on:
      branches:
        only:
          - master
      pull_requests: true

script:
  - python -m pip install -r requirements.txt -r dev-requirements.txt
  - command: 'pytest tests/integration/'
    on:
      changes:
        - ./armonaut/**

```
